services:
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: jenkins
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock