name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest

        INSTALL_DIR="/usr/local/bin"
        json=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest)
        url=$(echo "$json" | jq -r '.assets[].browser_download_url | select(contains("linux64") and endswith("gz"))')
        curl -s -L "$url" | tar -xz
        chmod +x geckodriver
        sudo mv geckodriver "$INSTALL_DIR"
        echo "installed geckodriver binary in $INSTALL_DIR"
        sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0 gobject-introspection libgirepository1.0-dev
        sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        rfbrowser init
    - name: Run tests
      run: |
        robot -d results --log index.html TestCases 

    - name: Store Artifact
      uses: actions/upload-artifact@v4
      if: success() || failure() 
      with:
        name: test-results
        path: |
            results

    - name: Report results
      if: success() || failure() 
      run: |
        pip install -r requirements.txt
        python Resources/Libs/GithubReporter.py results/output.xml $GITHUB_STEP_SUMMARY

      
