# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        robot -d results TestCases
    - name: Store Artifact
      uses: actions/upload-artifact@v4
      if: success() || failure() 
      with:
        name: test-results
        path: |
          results
    - name: Report results
      if: success() || failure() 
      run: |
        pip install -r requirements.txt
        python Resources/Libs/GithubReporter.py results/output.xml $GITHUB_STEP_SUMMARY