name: Robot Framework CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
    Run-Test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - uses: actions/cache@v4
          id: cache
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        - name: Install pip dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run Test
          run: python -m robot --outputdir results TestCases
        - name: Run Test and create report
          run: python -m robot -d reports -x junit-report.xml "TestCases"
        - name: Run Robot Framework tests and generate report
          run: |
             echo "ROBOT_RC=$?" >> "$GITHUB_ENV"  
              if: env.ROBOT_RC != '0'
              run: |
                echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
                exit 1
        - name: Publish test results
          uses: actions/upload-artifact@v4
          with:
            name: robot-test-results
            path: results
